### ISSUE TITLE
已设置 API_KEY 仍然提示 “Unable to fetch weather data.”

### ISSUE THREAD

**Issue by yanranxiaoxi** [qier222/oh-weather#1]
已测试 API_KEY 可用，直接访问 OpenWeatherMap API 可以返回正确数据
![image](https://user-images.githubusercontent.com/10684000/108763821-c8d1dc80-758c-11eb-9818-86bda9b4c12f.png)
![image](https://user-images.githubusercontent.com/10684000/108764438-91affb00-758d-11eb-8930-982ac47b7511.png)

**Comment by qier222** [comment]
那个api目录下的js文件是serverless函数，需要部署到netlify或vercel才会生效的。
你可以找找看有没有在本地运行serveless函数的方法。

**Comment by yanranxiaoxi** [comment]
感谢！
